config/routes.rb
Rails.application.routes.draw do
  get 'evaluate_assets/show/:id', to: 'evaluate_assets#show'

  patch 'evaluate_assets/update/:id', to: 'evaluate_assets#update'

  resources :assets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer_question.rb
class AnswerQuestion
  def initialize(asset, question_id, answer, question_list = nil)
    @asset = asset
    @question_id = question_id
    @answer = answer
    @question_list = question_list
  end

  def answer
    @asset.evaluation[@question_id] = @answer
    response = @question_list.dig(@question_id, @answer)
    if response.match(/grade=/)
      @asset.grade = response.split('=')[1]
      {"complete" => true}
    else
      {"complete" => false}
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
  serialize :evaluation, JSON
  after_initialize :set_defaults

  def set_defaults
    self.evaluation ||= {}
  end
end

app/models/next_question.rb
class NextQuestion
  def initialize(asset, question_id, question_list = nil)
    @asset = asset
    @question_id = question_id
    @question_list = question_list
  end

  def next
    if @question_id.nil? || @asset.evaluation.empty?
      first_question_id = @question_list.find{|k,v| v["first"]}&.[](0)
      {"next_question_id" => first_question_id}
    else
      answer = @asset.evaluation.fetch(@question_id)
      response = @question_list.dig(@question_id, answer)

      if response.match(/grade=/)
        {"next_question_id" => nil}
      else
        {"next_question_id" => response}
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_action :set_asset, only: [:show, :edit, :update, :destroy]

  # GET /assets
  # GET /assets.json
  def index
    @assets = Asset.all
  end

  # GET /assets/1
  # GET /assets/1.json
  def show
  end

  # GET /assets/new
  def new
    @asset = Asset.new
  end

  # GET /assets/1/edit
  def edit
  end

  # POST /assets
  # POST /assets.json
  def create
    @asset = Asset.new(asset_params)

    respond_to do |format|
      if @asset.save
        format.html { redirect_to url_for(controller: "evaluate_assets", action: 'show', id: @asset.id), 
                      notice: 'Asset was successfully created. Please evaluate it.' }
        format.json { render :show, status: :created, location: @asset }
      else
        format.html { render :new }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assets/1
  # PATCH/PUT /assets/1.json
  def update
    respond_to do |format|
      if @asset.update(asset_params)
        format.html { redirect_to @asset, notice: 'Asset was successfully updated.' }
        format.json { render :show, status: :ok, location: @asset }
      else
        format.html { render :edit }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset.destroy
    respond_to do |format|
      format.html { redirect_to assets_url, notice: 'Asset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asset
      @asset = Asset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asset_params
      params.require(:asset).permit(:name)
    end
end

app/controllers/evaluate_assets_controller.rb
class EvaluateAssetsController < ApplicationController
  before_action :set_asset

  QUESTION_LIST = {
    "housing_cracked" =>{"first" => true, "text" => "Is the housing cracked?", "yes" => "grade=D", "no" => "lcd_scratches"},
    "lcd_scratches" =>{"text" => "Does the LCD have deep scratches?", "yes" => "grade=C", "no" => "dents_in_housing"},
    "dents_in_housing" =>{"text" => "Are there dents in the housing?", "yes" => "grade=C", "no" => "minor_lcd_scratches"},
    "minor_lcd_scratches" =>{"text" => "Are there more than 20 scratches on LCD?", "yes" => "grade=B", "no" => "phone_scratches"},
    "phone_scratches" =>{"text" => "Does the phone have scratches?", "yes" => "grade=A", "no" => "grade=A+"},
  }

  def show
    set_next_question
  end

  def update
    result = AnswerQuestion.new(@asset, params["question_id"], params["response"], QUESTION_LIST).answer
    @asset.save!

    if result["complete"]
      flash[:notice] = "Your grade has been updated!"
      redirect_to asset_url(@asset)
    else
      set_next_question(params["question_id"])
      render "show.html"
    end
  end

private
  def set_asset
    @asset = Asset.find(params[:id])
  end

  def set_next_question(question_id=nil)
    next_question = NextQuestion.new(@asset, question_id, QUESTION_LIST).next
    @question_id = next_question["next_question_id"]
    @question_text = QUESTION_LIST.dig(@question_id, "text")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/evaluate_assets_helper.rb
module EvaluateAssetsHelper
end

app/views/assets/_form.html.erb
<%= form_with(model: asset, local: true) do |form| %>
  <% if asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% asset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>


    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>:
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/assets/edit.html.erb
<h1>Editing Asset</h1>

<%= render 'form', asset: @asset %>

<%= link_to 'Show', @asset %> |
<%= link_to 'Back', assets_path %>

app/views/assets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Assets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assets.each do |asset| %>
      <tr>
        <td><%= asset.name %>
        <td><%= link_to 'Show', asset %></td>
        <td><%= link_to 'Edit', edit_asset_path(asset) %></td>
        <td><%= link_to 'Destroy', asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asset', new_asset_path %>

app/views/assets/new.html.erb
<h1>New Asset</h1>

<%= render 'form', asset: @asset %>

<%= link_to 'Back', assets_path %>

app/views/assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>Name: <%= @asset.name %></p>
<p>Grade: <%= @asset.grade %></p>
<p>Evaluation: <%= @asset.evaluation %></p>

<%= link_to 'Edit', edit_asset_path(@asset) %> |
<%= link_to 'Evaluate', url_for(controller: "evaluate_assets", action: 'show', id: @asset.id) %> |
<%= link_to 'Back', assets_path %>

app/views/evaluate_assets/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Asset: <%= @asset.name %></h1>
<%= form_for @asset,
             url: url_for(controller: "evaluate_assets", action: 'update', id: @asset.id) do |f| %>
   <p><%= @question_text %></p>
  <input type="hidden" name="question_id" value=<%= @question_id %>>
  <input type="submit" name="response" value="yes">
  <input type="submit" name="response" value="no">
<% end %>

app/views/evaluate_assets/update.html.erb
<h1>EvaluateAssets#update</h1>
<p>Find me in app/views/evaluate_assets/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TstRailsNew</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>